import type { AnalysisResult } from "@/types";

export function generateReportText(result: AnalysisResult): string {
  const divider = "─".repeat(50);
  const lines: string[] = [];

  lines.push("TRUTH BUDDY — FILE AUTHENTICITY REPORT");
  lines.push(divider);
  lines.push(`File: ${result.fileName}`);
  lines.push(`Type: ${result.fileType.toUpperCase()}`);
  lines.push(`Date: ${new Date(result.createdAt).toLocaleString()}`);
  if (result.completedAt) {
    const elapsed = Math.round(
      (new Date(result.completedAt).getTime() - new Date(result.createdAt).getTime()) / 1000
    );
    lines.push(`Analysis Time: ${elapsed}s`);
  }
  lines.push(divider);
  lines.push("");
  lines.push(`TRUST SCORE: ${result.confidenceScore}/100`);
  lines.push(`VERDICT: ${result.authenticityLevel.toUpperCase()}`);
  lines.push("");
  lines.push(`Summary: ${result.summary}`);
  lines.push("");
  lines.push(divider);
  lines.push("DETAILED FINDINGS");
  lines.push(divider);

  result.details.forEach((d: any, i: number) => {
    lines.push(`${i + 1}. [${d.severity.toUpperCase()}] ${d.category}`);
    lines.push(`   Finding: ${d.finding}`);
    lines.push(`   ${d.description}`);
    lines.push("");
  });

  if (result.exifData && Object.keys(result.exifData).length > 0) {
    lines.push(divider);
    lines.push("METADATA");
    lines.push(divider);
    Object.entries(result.exifData).forEach(([k, v]) => {
      lines.push(`  ${k}: ${v}`);
    });
    lines.push("");
  }

  if (result.hashInfo) {
    lines.push(divider);
    lines.push("FILE INTEGRITY");
    lines.push(divider);
    lines.push(`  SHA-256: ${result.hashInfo.sha256}`);
    if (result.hashInfo.md5 && result.hashInfo.md5 !== "n/a") {
      lines.push(`  MD5: ${result.hashInfo.md5}`);
    }
    lines.push(`  Modified: ${result.hashInfo.isModified ? "Yes" : "No"}`);
    lines.push("");
  }

  lines.push(divider);
  lines.push("Generated by Truth Buddy • truthbuddy.app");
  lines.push(`Report ID: ${result.id}`);

  return lines.join("\n");
}

export function downloadReport(result: AnalysisResult) {
  const text = generateReportText(result);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `truthbuddy-report-${result.fileName.replace(/\.[^.]+$/, "")}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function shareAnalysis(result: AnalysisResult) {
  const shareData = {
    title: `Truth Buddy Report: ${result.fileName}`,
    text: `${result.fileName} — ${result.authenticityLevel.toUpperCase()} (${result.confidenceScore}/100). ${result.summary}`,
    url: window.location.href,
  };

  if (navigator.share) {
    try {
      await navigator.share(shareData);
      return true;
    } catch {
      // User cancelled or share failed, fall through to clipboard
    }
  }

  // Fallback: copy link
  await navigator.clipboard.writeText(window.location.href);
  return false; // indicates clipboard fallback was used
}
